#!/usr/bin/env node
/**
 * Regenerates docs/index.html from the @dsCard headers on every specimen.
 * The gallery is a shell around the specimens, never a copy of them — it
 * iframes each file in place, so it cannot drift from source.
 * Zero dependencies. Deterministic: same input -> byte-identical output.
 */
import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GROUP_ORDER = ['Colors', 'Type', 'Spacing', 'Effects', 'Brand', 'Components', 'Website'];

function walk(dir, keep, out = []) {
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (e.name.startsWith('.') || e.name === 'node_modules') continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, keep, out);
    else if (keep(p)) out.push(p);
  }
  return out;
}

const esc = (s = '') => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const attr = (s, k) => (s.match(new RegExp(k + '="([^"]*)"')) || [])[1];

const files = [
  ...walk(join(ROOT, 'guidelines'), (p) => p.endsWith('.html')),
  ...walk(join(ROOT, 'components'), (p) => p.endsWith('.card.html')),
  ...walk(join(ROOT, 'ui_kits'), (p) => p.endsWith('index.html')),
];

const cards = [];
for (const p of files) {
  const m = readFileSync(p, 'utf8').slice(0, 800).match(/<!--\s*@dsCard\s+([\s\S]*?)-->/);
  if (!m) continue;
  const [w, h] = (attr(m[1], 'viewport') || '700x200').split('x').map(Number);
  cards.push({
    group: attr(m[1], 'group') || 'Other',
    name: attr(m[1], 'name') || relative(ROOT, p),
    subtitle: attr(m[1], 'subtitle') || '',
    src: '../' + relative(ROOT, p).split('\\').join('/'),
    w, h,
  });
}

const groups = [...new Set(cards.map((c) => c.group))].sort(
  (a, b) => (GROUP_ORDER.indexOf(a) + 1 || 99) - (GROUP_ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b)
);

const section = (g) => {
  const items = cards.filter((c) => c.group === g).sort((a, b) => a.name.localeCompare(b.name));
  return `<section id="${esc(g.toLowerCase())}">
  <h2>${esc(g)}<span class="count">${items.length}</span></h2>
${items.map((c) => `  <article class="card">
    <header><h3>${esc(c.name)}</h3>${c.subtitle ? `<p>${esc(c.subtitle)}</p>` : ''}<span class="vp">${c.w}\u00d7${c.h}</span></header>
    <div class="frame" style="--vw:${c.w};--vh:${c.h}"><iframe src="${esc(c.src)}" width="${c.w}" height="${c.h}" loading="lazy" title="${esc(c.name)}"></iframe></div>
  </article>`).join('\n')}
</section>`;
};

const html = `<!DOCTYPE html>
<!-- GENERATED by scripts/build-docs.mjs — do not edit by hand. -->
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>axelerate \u00b7 design system</title>
<link rel="stylesheet" href="../styles.css">
<style>
body{margin:0;background:var(--surface-page)}
.wrap{max-width:1160px;margin:0 auto;padding:0 24px}
header.top{padding:64px 0 40px}
.wm{font-family:var(--font-display);font-weight:800;font-size:var(--text-5xl);letter-spacing:-.04em;color:var(--violet-600);line-height:1;display:block}
.lede{font-size:18px;color:var(--text-secondary);max-width:52ch;margin:14px 0 0}
.note{font-family:var(--font-hand);font-size:19px;color:var(--gray-600);transform:rotate(-1.5deg);display:inline-block;margin-top:22px}
nav{position:sticky;top:0;z-index:20;background:rgba(255,255,255,.85);backdrop-filter:blur(10px);border-bottom:1px solid var(--gray-100);padding:12px 0}
nav .wrap{display:flex;gap:8px;flex-wrap:wrap}
nav a{font-family:var(--font-label);font-size:11px;font-weight:700;letter-spacing:.07em;text-transform:uppercase;text-decoration:none;color:var(--text-primary);background:var(--gray-0);padding:7px 13px;border-radius:999px;box-shadow:var(--sticker-cut),var(--shadow-paper);transition:transform var(--dur-fast) var(--ease-launch)}
nav a:hover{transform:translate(-1px,-2px) rotate(-1deg);color:var(--text-brand)}
section{padding:52px 0 8px;border-top:1px solid var(--gray-100)}
h2{font-family:var(--font-display);font-size:var(--text-3xl);font-weight:800;letter-spacing:-.03em;margin:0 0 26px;display:flex;align-items:baseline;gap:12px}
.count{font-family:var(--font-label);font-size:11px;font-weight:500;letter-spacing:.07em;color:var(--gray-500);font-feature-settings:'tnum'}
.card{margin:0 0 34px}
.card header{margin:0 0 10px;display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}
.card h3{font-family:var(--font-display);font-size:17px;font-weight:700;letter-spacing:-.01em;margin:0}
.card header p{margin:0;font-size:14px;color:var(--text-secondary);flex:1 1 260px}
.vp{font-family:var(--font-label);font-size:10px;font-weight:500;letter-spacing:.06em;color:var(--gray-500);font-feature-settings:'tnum'}
.frame{width:100%;overflow:hidden;background:var(--surface-card);border-radius:var(--radius-hand-sm);box-shadow:var(--shadow-paper)}
.frame iframe{border:0;display:block;transform-origin:0 0}
footer{padding:56px 0 72px;border-top:1px solid var(--gray-100);margin-top:40px;color:var(--gray-600);font-size:14px}
</style></head>
<body class="ax-grid-paper">
<div class="wrap"><header class="top">
  <span class="wm">axelerate</span>
  <p class="lede">Tokens, components, and brand foundations \u2014 every card below is the live specimen file, rendered in place.</p>
  <span class="note">generated from the specimens \u2014 never hand-edited</span>
</header></div>
<nav><div class="wrap">${groups.map((g) => `<a href="#${esc(g.toLowerCase())}">${esc(g)}</a>`).join('')}</div></nav>
<div class="wrap">
${groups.map(section).join('\n')}
<footer>${cards.length} specimens \u00b7 regenerate with <code>npm run docs</code></footer>
</div>
<script>
function fit(){
  for (const f of document.querySelectorAll('.frame')) {
    const vw = +f.style.getPropertyValue('--vw'), vh = +f.style.getPropertyValue('--vh');
    const s = Math.min(1, f.clientWidth / vw);
    f.querySelector('iframe').style.transform = 'scale(' + s + ')';
    f.style.height = Math.round(vh * s) + 'px';
  }
}
addEventListener('resize', fit); addEventListener('load', fit); fit();
</script>
</body></html>
`;

mkdirSync(join(ROOT, 'docs'), { recursive: true });
writeFileSync(join(ROOT, 'docs', 'index.html'), html);
console.log(`docs/index.html \u2014 ${cards.length} cards across ${groups.length} groups: ${groups.join(', ')}`);
